// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActorInspect(arg1, arg2) {
  return window['go']['main']['App']['ActorInspect'](arg1, arg2);
}

export function ChatHistory() {
  return window['go']['main']['App']['ChatHistory']();
}

export function ChatHistorySegment(arg1) {
  return window['go']['main']['App']['ChatHistorySegment'](arg1);
}

export function ClipboardGetImage() {
  return window['go']['main']['App']['ClipboardGetImage']();
}

export function ContextUsage() {
  return window['go']['main']['App']['ContextUsage']();
}

export function DeleteChatTurn(arg1, arg2) {
  return window['go']['main']['App']['DeleteChatTurn'](arg1, arg2);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function NotificationSound() {
  return window['go']['main']['App']['NotificationSound']();
}

export function NotificationSoundForRole(arg1) {
  return window['go']['main']['App']['NotificationSoundForRole'](arg1);
}

export function OpenAttachment(arg1) {
  return window['go']['main']['App']['OpenAttachment'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function PickWorkspaceFolder(arg1) {
  return window['go']['main']['App']['PickWorkspaceFolder'](arg1);
}

export function PingCore() {
  return window['go']['main']['App']['PingCore']();
}

export function ReadDroppedFile(arg1) {
  return window['go']['main']['App']['ReadDroppedFile'](arg1);
}

export function ResumeTask(arg1, arg2) {
  return window['go']['main']['App']['ResumeTask'](arg1, arg2);
}

export function RetryChatTurn(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetryChatTurn'](arg1, arg2, arg3);
}

export function RuntimeStatus() {
  return window['go']['main']['App']['RuntimeStatus']();
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SetWorkspace(arg1, arg2) {
  return window['go']['main']['App']['SetWorkspace'](arg1, arg2);
}

export function SlashSuggest(arg1) {
  return window['go']['main']['App']['SlashSuggest'](arg1);
}

export function SocketPath() {
  return window['go']['main']['App']['SocketPath']();
}

export function SteerChat(arg1, arg2) {
  return window['go']['main']['App']['SteerChat'](arg1, arg2);
}

export function StopChat(arg1) {
  return window['go']['main']['App']['StopChat'](arg1);
}

export function SubmitFeedback(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitFeedback'](arg1, arg2, arg3, arg4);
}

export function SwitchSession(arg1) {
  return window['go']['main']['App']['SwitchSession'](arg1);
}

export function SyncInputShape(arg1) {
  return window['go']['main']['App']['SyncInputShape'](arg1);
}

export function TaskInspect(arg1, arg2) {
  return window['go']['main']['App']['TaskInspect'](arg1, arg2);
}
