// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatHistory() {
  return window['go']['main']['App']['ChatHistory']();
}

export function ContextUsage() {
  return window['go']['main']['App']['ContextUsage']();
}

export function PingCore() {
  return window['go']['main']['App']['PingCore']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SlashSuggest(arg1) {
  return window['go']['main']['App']['SlashSuggest'](arg1);
}

export function SocketPath() {
  return window['go']['main']['App']['SocketPath']();
}

export function SyncInputShape(arg1) {
  return window['go']['main']['App']['SyncInputShape'](arg1);
}
