// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function ChatHistory():Promise<main.chatHistoryResult>;

export function ContextUsage():Promise<main.chatUsage>;

export function DeleteChatTurn(arg1:string,arg2:number):Promise<void>;

export function PingCore():Promise<main.pingResult>;

export function ReadDroppedFile(arg1:string):Promise<main.droppedFile>;

export function RetryChatTurn(arg1:string,arg2:number):Promise<main.chatResult>;

export function SendMessage(arg1:string,arg2:string):Promise<main.chatResult>;

export function SlashSuggest(arg1:string):Promise<Array<config.CommandEntry>>;

export function SocketPath():Promise<string>;

export function SyncInputShape(arg1:boolean):Promise<void>;
