// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function ActorInspect(arg1:string,arg2:number):Promise<main.taskInspectResult>;

export function ChatHistory():Promise<main.chatHistoryResult>;

export function ClipboardGetImage():Promise<main.clipboardImage>;

export function ContextUsage():Promise<main.chatUsage>;

export function DeleteChatTurn(arg1:string,arg2:number):Promise<void>;

export function DeleteSession(arg1:string):Promise<main.sessionDeleteResult>;

export function ListSessions():Promise<main.sessionListResult>;

export function NewSession():Promise<main.sessionDeleteResult>;

export function NotificationSound():Promise<string>;

export function NotificationSoundForRole(arg1:string):Promise<string>;

export function OpenAttachment(arg1:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function PickWorkspaceFolder(arg1:string):Promise<string>;

export function PingCore():Promise<main.pingResult>;

export function ReadDroppedFile(arg1:string):Promise<main.droppedFile>;

export function ResumeTask(arg1:string,arg2:string):Promise<void>;

export function RetryChatTurn(arg1:string,arg2:number):Promise<main.chatResult>;

export function RuntimeStatus():Promise<main.runtimeStatus>;

export function SendMessage(arg1:string,arg2:string):Promise<main.chatResult>;

export function SetWorkspace(arg1:string,arg2:string):Promise<main.workspaceSetResult>;

export function SlashSuggest(arg1:string):Promise<Array<config.CommandEntry>>;

export function SocketPath():Promise<string>;

export function SteerChat(arg1:string,arg2:string):Promise<void>;

export function StopChat(arg1:string):Promise<void>;

export function SubmitFeedback(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function SwitchSession(arg1:string):Promise<string>;

export function SyncInputShape(arg1:boolean):Promise<void>;

export function TaskInspect(arg1:string,arg2:number):Promise<main.taskInspectResult>;
